repos:
  # Ruff (Python linter & formatter)
  - repo: https://github.com/charliermarsh/ruff-pre-commit
    rev: v0.12.3  # Ruff のバージョン
    hooks:
      - id: ruff
        args: [--fix, --exit-non-zero-on-fix]
      - id: ruff-format

  # Local hook: run pytest before every commit
  - repo: local
    hooks:
      - id: pytest
        name: pytest
        entry: uv run pytest
        language: system
        types: [python]
        pass_filenames: false
        